"""
AttendanceSafe backend — calculates how many classes a student can bunk
while staying at or above a target attendance percentage (default 75%).

Two entry points:
  POST /calculate-manual  -> user types in numbers
  POST /calculate-ai      -> user uploads a screenshot; Groq's vision model
                             reads the numbers off it, then we run the SAME
                             math as the manual path.

Run locally:
    pip install -r requirements.txt
    uvicorn main:app --reload --port 8000
"""

import os
import io
import math
import base64
import json
import asyncio
import re
from typing import Optional
from pathlib import Path

from fastapi import FastAPI, UploadFile, File, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from dotenv import load_dotenv
from groq import Groq, RateLimitError, APIStatusError
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded
from PIL import Image, ImageOps, ImageEnhance, ImageFilter

# Support HEIC/HEIF format commonly generated by iPhones
try:
    import pillow_heif
    pillow_heif.register_heif_opener()
except ImportError:
    pass

# Load .env file reliably from the backend directory
env_path = Path(__file__).resolve().parent / ".env"
load_dotenv(dotenv_path=env_path, override=True)

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
GROQ_VISION_MODEL = os.environ.get("GROQ_VISION_MODEL", "qwen/qwen3.6-27b")
TARGET_PERCENTAGE = float(os.environ.get("TARGET_PERCENTAGE", 75))

AI_RATE_LIMIT = os.environ.get("AI_RATE_LIMIT", "30/minute")
MAX_CONCURRENT_AI_CALLS = int(os.environ.get("MAX_CONCURRENT_AI_CALLS", "10"))

groq_client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None
ai_call_semaphore = asyncio.Semaphore(MAX_CONCURRENT_AI_CALLS)

def get_groq_client() -> Optional[Groq]:
    global groq_client
    if groq_client is None:
        key = os.environ.get("GROQ_API_KEY")
        if key:
            groq_client = Groq(api_key=key)
    return groq_client

def get_gemini_key() -> Optional[str]:
    return os.environ.get("GEMINI_API_KEY")

if not GROQ_API_KEY and not GEMINI_API_KEY:
    print("WARNING: Neither GROQ_API_KEY nor GEMINI_API_KEY is set. /calculate-ai will not work until one is configured.")

def get_real_ip(request: Request) -> str:
    """Extract real client IP behind reverse proxies (Render, Cloudflare, Nginx)"""
    forwarded = request.headers.get("X-Forwarded-For")
    if forwarded:
        return forwarded.split(",")[0].strip()
    return get_remote_address(request) or "127.0.0.1"

limiter = Limiter(key_func=get_real_ip)

app = FastAPI(title="AttendanceSafe API")
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------- Request / response models ----------

class ManualRequest(BaseModel):
    total: int = Field(..., ge=0, description="Total classes held so far")
    attended: int = Field(..., ge=0, description="Classes attended so far")
    remaining: Optional[int] = Field(
        None, ge=0, description="Classes still remaining this semester, if known"
    )


class CalculationResult(BaseModel):
    total_classes: int
    attended_classes: int
    current_percentage: float
    target_percentage: float
    max_bunks: int
    classes_needed: Optional[int] = None
    message: str


# ---------- Core math (shared by both endpoints) ----------

def calculate_result(total: int, attended: int, remaining: Optional[int]) -> CalculationResult:
    if total == 0:
        raise HTTPException(
            status_code=422,
            detail="Total classes held can't be zero — there's nothing to calculate yet.",
        )
    if attended > total:
        raise HTTPException(
            status_code=422,
            detail="Attended classes can't be more than total classes held.",
        )

    target = TARGET_PERCENTAGE / 100.0
    current_percentage = round((attended / total) * 100, 2)

    # Case B: we know how many classes are still coming up this semester.
    if remaining:
        x = attended + remaining - target * (total + remaining)
        if x >= 0:
            max_bunks = math.floor(x)
            message = (
                f"You're on track. You can skip up to {max_bunks} of your "
                f"remaining {remaining} classes and still finish at "
                f"{TARGET_PERCENTAGE:.0f}% attendance."
            )
            return CalculationResult(
                total_classes=total,
                attended_classes=attended,
                current_percentage=current_percentage,
                target_percentage=TARGET_PERCENTAGE,
                max_bunks=max_bunks,
                classes_needed=None,
                message=message,
            )
        else:
            classes_needed = 0
            message = (
                f"Even attending all {remaining} remaining classes will keep you "
                f"below {TARGET_PERCENTAGE:.0f}%. Attend every remaining class to "
                f"minimize the shortfall."
            )
            return CalculationResult(
                total_classes=total,
                attended_classes=attended,
                current_percentage=current_percentage,
                target_percentage=TARGET_PERCENTAGE,
                max_bunks=0,
                classes_needed=classes_needed,
                message=message,
            )

    # Case A: no "remaining" count given — just check current standing.
    max_bunks_raw = math.floor(attended / target) - total
    if max_bunks_raw >= 0:
        message = (
            f"You're currently at {current_percentage}%. Based on classes held so far, "
            f"you had room to miss {max_bunks_raw} more (already-held) classes and "
            f"still be at {TARGET_PERCENTAGE:.0f}%."
        )
        return CalculationResult(
            total_classes=total,
            attended_classes=attended,
            current_percentage=current_percentage,
            target_percentage=TARGET_PERCENTAGE,
            max_bunks=max_bunks_raw,
            classes_needed=None,
            message=message,
        )
    else:
        n = 0
        attended_f, total_f = attended, total
        while (attended_f + n) / (total_f + n) < target and n < 100000:
            n += 1
        message = (
            f"You're currently at {current_percentage}%, below the "
            f"{TARGET_PERCENTAGE:.0f}% target. Attend the next {n} classes "
            f"in a row (with no more misses) to get back to target."
        )
        return CalculationResult(
            total_classes=total,
            attended_classes=attended,
            current_percentage=current_percentage,
            target_percentage=TARGET_PERCENTAGE,
            max_bunks=0,
            classes_needed=n,
            message=message,
        )


def process_image_for_vision(image_bytes: bytes, filename: str = "", content_type: str = "") -> str:
    """
    Intelligently enhances low-quality, blurry, or low-contrast screenshots:
    - Auto-corrects EXIF rotation (critical for phone photos/screenshots)
    - Upscales small/low-res images with Lanczos so small font digits become legible
    - Applies UnsharpMask deblurring to restore sharp character edges
    - Normalizes lighting and contrast with autocontrast to make faint/dim text pop
    - Resizes to optimal 1200px max dimension for high token efficiency & fast response
    """
    if content_type and not (
        content_type.startswith("image/")
        or content_type in ("application/octet-stream", "")
    ):
        raise HTTPException(
            status_code=422,
            detail="Please upload a JPEG, PNG, or WEBP screenshot.",
        )

    try:
        img = Image.open(io.BytesIO(image_bytes))
        
        # 1. Orientation correction
        img = ImageOps.exif_transpose(img)
        
        # 2. RGB normalization
        if img.mode not in ("RGB", "L"):
            img = img.convert("RGB")
        elif img.mode == "L":
            img = img.convert("RGB")
        
        w, h = img.size
        
        # 3. Adaptive resolution scaling:
        if min(w, h) < 750:
            scale = min(2.2, 950.0 / max(min(w, h), 1))
            new_w, new_h = int(w * scale), int(h * scale)
            img = img.resize((new_w, new_h), Image.Resampling.LANCZOS)
        elif max(w, h) > 1200:
            img.thumbnail((1200, 1200), Image.Resampling.LANCZOS)
            
        # 4. Auto-contrast stretching
        try:
            img = ImageOps.autocontrast(img, cutoff=2)
        except Exception:
            pass
            
        # 5. Multi-scale UnsharpMask filter to deblur character strokes
        try:
            img = img.filter(ImageFilter.UnsharpMask(radius=2, percent=220, threshold=2))
        except Exception:
            pass

        # 6. Sharpness boost
        try:
            sharpness = ImageEnhance.Sharpness(img)
            img = sharpness.enhance(1.8)
        except Exception:
            pass

        # 7. Contrast boost
        try:
            contrast = ImageEnhance.Contrast(img)
            img = contrast.enhance(1.3)
        except Exception:
            pass
            
        buffer = io.BytesIO()
        img.save(buffer, format="JPEG", quality=88, optimize=True)
        compressed_bytes = buffer.getvalue()
        b64_image = base64.b64encode(compressed_bytes).decode("utf-8")
        return f"data:image/jpeg;base64,{b64_image}"
    except HTTPException:
        raise
    except Exception:
        b64_image = base64.b64encode(image_bytes).decode("utf-8")
        return f"data:image/jpeg;base64,{b64_image}"


def safe_int(val) -> int:
    if val is None:
        return 0
    if isinstance(val, (int, float)):
        return int(val)
    if isinstance(val, str):
        # Ignore percentage strings (e.g. '85%', '100.0%') so they don't corrupt class counts
        if '%' in val:
            return 0
        m = re.search(r'\d+', val)
        if m:
            return int(m.group(0))
    return 0


def get_row_numbers(row: dict) -> tuple[int, int]:
    """
    Extracts conducted (held) and attended (present) counts from a row dictionary.
    Excludes percentage columns, library weightage, credit hours, and serial numbers.
    """
    if not isinstance(row, dict):
        return 0, 0

    name = str(row.get("subject", row.get("name", row.get("course", "")))).lower()
    if any(k in name for k in ["library", "weightage", "remedial", "non-academic", "lib -", "lib-"]):
        return 0, 0

    cleaned_items = {}
    for k, v in row.items():
        k_low = k.lower().strip()
        # Strictly ignore percentage columns, absents, serials, codes, grades
        if any(x in k_low for x in ["percent", "%", "pct", "absent", "grade", "credit", "sno", "sr", "code", "subject", "name", "course"]):
            continue
        cleaned_items[k_low] = v

    att = 0
    tot = 0

    # 1. Match attended/present
    for k_low, v in cleaned_items.items():
        val = safe_int(v)
        if val <= 0:
            continue
        if any(x in k_low for x in ["present", "attended", "classes_attended", "att_classes", "cleared", "total_attended"]):
            att = val
            break

    # 2. Match conducted/held/total
    for k_low, v in cleaned_items.items():
        val = safe_int(v)
        if val <= 0:
            continue
        if any(x in k_low for x in ["conduct", "held", "total_classes", "classes_held", "total_conducted", "delivered", "max", "scheduled"]):
            tot = val
            break

    # 3. Fallbacks
    if tot == 0:
        for k_low, v in cleaned_items.items():
            if k_low == "total" or "total" in k_low:
                val = safe_int(v)
                if val > 0:
                    tot = val
                    break

    if att == 0:
        for k_low, v in cleaned_items.items():
            if k_low in ["att", "p"]:
                val = safe_int(v)
                if val > 0:
                    att = val
                    break

    return tot, att


def extract_attendance_numbers(raw_text: str) -> tuple[int, int]:
    """
    Deterministic attendance number extractor:
    1. Parses JSON objects or arrays of subjects.
    2. Excludes non-regular weightage rows (e.g. library attendance, remedial).
    3. Excludes percentage columns to prevent corrupted attendance calculations.
    4. Performs pure Python mathematical summation across valid academic course rows.
    """
    if not raw_text:
        return 0, 0

    cleaned = re.sub(r"<think>.*?</think>", "", raw_text, flags=re.DOTALL).strip()
    cleaned = cleaned.replace("```json", "").replace("```", "").strip()

    # 1. Greedy JSON Parsing
    json_match = re.search(r"(\[[\s\S]*\]|\{[\s\S]*\})", cleaned)
    if json_match:
        try:
            parsed = json.loads(json_match.group(0))

            # Case A: Dictionary containing a "subjects" list or top-level totals
            if isinstance(parsed, dict):
                if "subjects" in parsed and isinstance(parsed["subjects"], list) and len(parsed["subjects"]) > 0:
                    tot_sum = 0
                    att_sum = 0
                    for s in parsed["subjects"]:
                        t, a = get_row_numbers(s)
                        tot_sum += t
                        att_sum += a
                    if tot_sum > 0:
                        return tot_sum, att_sum

                # Check for explicit overall / grand total keys
                otot = None
                oatt = None
                for k in ["overall_total", "grand_total", "total_classes", "overall_conducted", "total", "held", "conducted"]:
                    if k in parsed:
                        val = safe_int(parsed[k])
                        if val > 0:
                            otot = val
                            break
                for k in ["overall_attended", "grand_attended", "attended_classes", "overall_present", "attended", "present"]:
                    if k in parsed:
                        val = safe_int(parsed[k])
                        if val >= 0:
                            oatt = val
                            break

                if otot is not None and oatt is not None and otot > 0:
                    return otot, oatt

            # Case B: Direct Array of subjects
            elif isinstance(parsed, list):
                tot_sum = 0
                att_sum = 0
                for s in parsed:
                    t, a = get_row_numbers(s)
                    tot_sum += t
                    att_sum += a
                if tot_sum > 0:
                    return tot_sum, att_sum
        except Exception:
            pass

    # 2. Key-Value Regex Matching
    tot_pattern = r"(?:total|held|conducted|delivered|max|classes_held|total_classes)(?:[^\d\n\r%]{1,25})(\d+)"
    att_pattern = r"(?:attend(?:ed)?|present|cleared|classes_attended|attended_classes)(?:[^\d\n\r%]{1,25})(\d+)"
    
    tot_matches = [int(x) for x in re.findall(tot_pattern, cleaned, re.IGNORECASE)]
    att_matches = [int(x) for x in re.findall(att_pattern, cleaned, re.IGNORECASE)]
    
    if tot_matches and att_matches:
        return tot_matches[-1], att_matches[-1]

    # 3. Fraction Matching
    fractions = re.findall(r"(\d+)\s*[/]\s*(\d+)", cleaned)
    if fractions:
        att_total = 0
        tot_total = 0
        for n_str, d_str in fractions:
            n, d = int(n_str), int(d_str)
            if 0 < d <= 500 and n <= d:
                att_total += n
                tot_total += d
        if tot_total > 0:
            return tot_total, att_total

    return 0, 0


async def query_gemini_vision(data_url: str, prompt: str, api_key: str) -> Optional[str]:
    """Direct HTTP client for Google Gemini Vision (gemini-2.5-flash / gemini-1.5-flash)"""
    try:
        parts = data_url.split(",", 1)
        if len(parts) != 2:
            return None
        b64_data = parts[1]
        mime_type = "image/jpeg"
        if "image/png" in parts[0]:
            mime_type = "image/png"

        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"
        payload = {
            "contents": [
                {
                    "parts": [
                        {"text": prompt},
                        {
                            "inlineData": {
                                "mimeType": mime_type,
                                "data": b64_data,
                            }
                        },
                    ]
                }
            ],
            "generationConfig": {
                "responseMimeType": "application/json",
                "temperature": 0.0,
            },
        }
        import httpx
        async with httpx.AsyncClient(timeout=25.0) as http_client:
            resp = await http_client.post(url, json=payload)
            if resp.status_code == 200:
                result_json = resp.json()
                return result_json["candidates"][0]["content"]["parts"][0]["text"]
    except Exception as e:
        print("Gemini Vision API error:", e)
    return None


# ---------- Endpoints ----------

@app.post("/calculate-manual", response_model=CalculationResult)
def calculate_manual(payload: ManualRequest):
    return calculate_result(payload.total, payload.attended, payload.remaining)


@app.post("/calculate-ai", response_model=CalculationResult)
@limiter.limit(AI_RATE_LIMIT)
async def calculate_ai(request: Request, file: UploadFile = File(...)):
    active_groq = get_groq_client()
    gemini_key = get_gemini_key()

    if not active_groq and not gemini_key:
        raise HTTPException(
            status_code=500,
            detail="Server is missing GROQ_API_KEY — AI mode is not configured.",
        )

    # Read uploaded file bytes
    image_bytes = await file.read()
    if not image_bytes or len(image_bytes) == 0:
        raise HTTPException(status_code=422, detail="Uploaded file is empty.")
    if len(image_bytes) > 25 * 1024 * 1024:
        raise HTTPException(status_code=422, detail="Image is too large (max 25MB).")

    # Normalize, auto-enhance, and generate clean JPEG data URL
    data_url = process_image_for_vision(
        image_bytes,
        filename=file.filename or "",
        content_type=file.content_type or "",
    )

    system_instruction = (
        "You are an expert OCR attendance parser. Analyze this attendance portal screenshot.\n"
        "Extract each academic course row as JSON:\n"
        "{\"subjects\": [{\"subject\": str, \"conducted\": <int>, \"attended\": <int>}, ...]}\n"
        "CRITICAL RULES:\n"
        "1. Do NOT confuse the percentage column with the attended classes count.\n"
        "2. Exclude non-academic rows like 'Library Attendance', 'Weightage', or 'Remedial'."
    )

    raw_text = ""
    last_error = None

    # Option 1: Try Gemini Vision if GEMINI_API_KEY is configured
    if gemini_key:
        gemini_result = await query_gemini_vision(data_url, system_instruction, gemini_key)
        if gemini_result:
            raw_text = gemini_result

    # Option 2: Try Groq Vision with auto-retries and model rotation
    if not raw_text and active_groq:
        models_to_try = [GROQ_VISION_MODEL]
        if "qwen/qwen3.8-27b" not in models_to_try:
            models_to_try.append("qwen/qwen3.8-27b")

        for model_name in models_to_try:
            for attempt in range(3):
                try:
                    async with ai_call_semaphore:
                        completion = await asyncio.to_thread(
                            active_groq.chat.completions.create,
                            model=model_name,
                            messages=[
                                {
                                    "role": "user",
                                    "content": [
                                        {"type": "text", "text": system_instruction},
                                        {"type": "image_url", "image_url": {"url": data_url}},
                                    ],
                                }
                            ],
                            max_tokens=600,
                            temperature=0,
                        )
                    if completion and completion.choices:
                        raw_text = str(completion.choices[0].message.content or "").strip()
                        break
                except RateLimitError as rle:
                    last_error = rle
                    if attempt < 2:
                        await asyncio.sleep(1.5 * (attempt + 1))
                    else:
                        break
                except Exception as e:
                    last_error = e
                    break
            if raw_text:
                break

    if not raw_text and last_error:
        if isinstance(last_error, RateLimitError):
            raise HTTPException(
                status_code=429,
                detail="AI quota limit briefly reached. Please wait a few moments before retrying, or enter your numbers manually.",
            )
        elif isinstance(last_error, APIStatusError):
            raise HTTPException(
                status_code=502,
                detail=f"The AI service returned an error ({last_error.status_code}). Try again shortly.",
            )
        else:
            raise HTTPException(
                status_code=502,
                detail=f"Couldn't reach the AI model right now ({last_error}). Try again shortly.",
            )

    total_classes, attended_classes = extract_attendance_numbers(raw_text)

    if total_classes <= 0:
        raise HTTPException(
            status_code=422,
            detail=(
                "Could not read the attendance data clearly from that screenshot. "
                "Try a clearer image, or enter your numbers manually."
            ),
        )

    return calculate_result(total_classes, attended_classes, None)


dist_dir = Path(__file__).resolve().parent.parent / "frontend" / "dist"
if (dist_dir / "assets").exists():
    app.mount("/assets", StaticFiles(directory=str(dist_dir / "assets")), name="assets")

@app.get("/")
def health_check(request: Request):
    dist_index = dist_dir / "index.html"
    if dist_index.exists() and "text/html" in request.headers.get("accept", ""):
        return FileResponse(dist_index)
    return {"status": "ok", "service": "AttendanceSafe API"}

@app.get("/health")
def api_health():
    return {"status": "ok", "service": "AttendanceSafe API"}
