"""
AttendanceSafe backend — calculates how many classes a student can bunk
while staying at or above a target attendance percentage (default 75%).

Two entry points:
  POST /calculate-manual  -> user types in numbers
  POST /calculate-ai      -> user uploads a screenshot; Groq's vision model
                             reads the numbers off it, then we run the SAME
                             math as the manual path.

Run locally:
    pip install -r requirements.txt
    uvicorn main:app --reload --port 8000
"""

import os
import io
import math
import base64
import json
import asyncio
import re
from typing import Optional
from pathlib import Path

from fastapi import FastAPI, UploadFile, File, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from dotenv import load_dotenv
from groq import Groq, RateLimitError, APIStatusError
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded
from PIL import Image, ImageOps

# Support HEIC/HEIF format commonly generated by iPhones
try:
    import pillow_heif
    pillow_heif.register_heif_opener()
except ImportError:
    pass

# Load .env file reliably from the backend directory
env_path = Path(__file__).resolve().parent / ".env"
load_dotenv(dotenv_path=env_path, override=True)

GROQ_API_KEY = os.environ.get("GROQ_API_KEY")
GROQ_VISION_MODEL = os.environ.get("GROQ_VISION_MODEL", "qwen/qwen3.6-27b")
TARGET_PERCENTAGE = float(os.environ.get("TARGET_PERCENTAGE", 75))

AI_RATE_LIMIT = os.environ.get("AI_RATE_LIMIT", "10/minute")
MAX_CONCURRENT_AI_CALLS = int(os.environ.get("MAX_CONCURRENT_AI_CALLS", "10"))

groq_client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None
ai_call_semaphore = asyncio.Semaphore(MAX_CONCURRENT_AI_CALLS)

def get_groq_client() -> Optional[Groq]:
    global groq_client
    if groq_client is None:
        key = os.environ.get("GROQ_API_KEY")
        if key:
            groq_client = Groq(api_key=key)
    return groq_client

if not GROQ_API_KEY:
    print("WARNING: GROQ_API_KEY is not set. /calculate-ai will not work until it is.")

limiter = Limiter(key_func=get_remote_address)

app = FastAPI(title="AttendanceSafe API")
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------- Request / response models ----------

class ManualRequest(BaseModel):
    total: int = Field(..., ge=0, description="Total classes held so far")
    attended: int = Field(..., ge=0, description="Classes attended so far")
    remaining: Optional[int] = Field(
        None, ge=0, description="Classes still remaining this semester, if known"
    )


class CalculationResult(BaseModel):
    current_percentage: float
    target_percentage: float
    max_bunks: int
    classes_needed: Optional[int] = None
    message: str


# ---------- Core math (shared by both endpoints) ----------

def calculate_result(total: int, attended: int, remaining: Optional[int]) -> CalculationResult:
    if total == 0:
        raise HTTPException(
            status_code=422,
            detail="Total classes held can't be zero — there's nothing to calculate yet.",
        )
    if attended > total:
        raise HTTPException(
            status_code=422,
            detail="Attended classes can't be more than total classes held.",
        )

    target = TARGET_PERCENTAGE / 100.0
    current_percentage = round((attended / total) * 100, 2)

    # Case B: we know how many classes are still coming up this semester.
    if remaining:
        x = attended + remaining - target * (total + remaining)
        if x >= 0:
            max_bunks = math.floor(x)
            message = (
                f"You're on track. You can skip up to {max_bunks} of your "
                f"remaining {remaining} classes and still finish at "
                f"{TARGET_PERCENTAGE:.0f}% attendance."
            )
            return CalculationResult(
                current_percentage=current_percentage,
                target_percentage=TARGET_PERCENTAGE,
                max_bunks=max_bunks,
                classes_needed=None,
                message=message,
            )
        else:
            classes_needed = 0
            message = (
                f"Even attending all {remaining} remaining classes will keep you "
                f"below {TARGET_PERCENTAGE:.0f}%. Attend every remaining class to "
                f"minimize the shortfall."
            )
            return CalculationResult(
                current_percentage=current_percentage,
                target_percentage=TARGET_PERCENTAGE,
                max_bunks=0,
                classes_needed=classes_needed,
                message=message,
            )

    # Case A: no "remaining" count given — just check current standing.
    max_bunks_raw = math.floor(attended / target) - total
    if max_bunks_raw >= 0:
        message = (
            f"You're currently at {current_percentage}%. Based on classes held so far, "
            f"you had room to miss {max_bunks_raw} more (already-held) classes and "
            f"still be at {TARGET_PERCENTAGE:.0f}%."
        )
        return CalculationResult(
            current_percentage=current_percentage,
            target_percentage=TARGET_PERCENTAGE,
            max_bunks=max_bunks_raw,
            classes_needed=None,
            message=message,
        )
    else:
        n = 0
        attended_f, total_f = attended, total
        while (attended_f + n) / (total_f + n) < target and n < 100000:
            n += 1
        message = (
            f"You're currently at {current_percentage}%, below the "
            f"{TARGET_PERCENTAGE:.0f}% target. Attend the next {n} classes "
            f"in a row (with no more misses) to get back to target."
        )
        return CalculationResult(
            current_percentage=current_percentage,
            target_percentage=TARGET_PERCENTAGE,
            max_bunks=0,
            classes_needed=n,
            message=message,
        )


def process_image_for_vision(image_bytes: bytes, filename: str = "", content_type: str = "") -> str:
    """
    Normalizes mobile photos/screenshots:
    - Auto-corrects EXIF rotation (critical for mobile phones)
    - Converts RGBA/P/HEIC/CMYK into crisp RGB JPEG
    - Resizes high-DPI screenshots (max 1800px) so payloads upload fast & never time out
    """
    if content_type and not (
        content_type.startswith("image/")
        or content_type in ("application/octet-stream", "")
    ):
        raise HTTPException(
            status_code=422,
            detail="Please upload a JPEG, PNG, or WEBP screenshot.",
        )

    try:
        img = Image.open(io.BytesIO(image_bytes))
        img = ImageOps.exif_transpose(img)
        if img.mode != "RGB":
            img = img.convert("RGB")
        
        max_dim = 1800
        if max(img.width, img.height) > max_dim:
            img.thumbnail((max_dim, max_dim), Image.Resampling.LANCZOS)
            
        buffer = io.BytesIO()
        img.save(buffer, format="JPEG", quality=88, optimize=True)
        compressed_bytes = buffer.getvalue()
        b64_image = base64.b64encode(compressed_bytes).decode("utf-8")
        return f"data:image/jpeg;base64,{b64_image}"
    except HTTPException:
        raise
    except Exception:
        # Fallback to direct raw base64 if PIL cannot parse (e.g., test mocks)
        b64_image = base64.b64encode(image_bytes).decode("utf-8")
        return f"data:image/jpeg;base64,{b64_image}"


# ---------- Endpoints ----------

@app.post("/calculate-manual", response_model=CalculationResult)
def calculate_manual(payload: ManualRequest):
    return calculate_result(payload.total, payload.attended, payload.remaining)


@app.post("/calculate-ai", response_model=CalculationResult)
@limiter.limit(AI_RATE_LIMIT)
async def calculate_ai(request: Request, file: UploadFile = File(...)):
    active_client = get_groq_client()
    if not active_client:
        raise HTTPException(
            status_code=500,
            detail="Server is missing GROQ_API_KEY — AI mode is not configured.",
        )

    # Read uploaded file bytes
    image_bytes = await file.read()
    if not image_bytes or len(image_bytes) == 0:
        raise HTTPException(status_code=422, detail="Uploaded file is empty.")
    if len(image_bytes) > 25 * 1024 * 1024:
        raise HTTPException(status_code=422, detail="Image is too large (max 25MB).")

    # Normalize image and generate clean JPEG data URL
    data_url = process_image_for_vision(
        image_bytes,
        filename=file.filename or "",
        content_type=file.content_type or "",
    )

    system_instruction = (
        "You are an expert OCR attendance parser. Analyze this attendance portal or mobile app screenshot. "
        "Extract ONLY: 'total_classes' (total classes held/conducted across all subjects) and 'attended_classes' (classes attended/present). "
        "If multiple subjects or course rows are shown in a table, calculate the sum of total classes held and the sum of attended classes across all subjects. "
        "If overall summary counts are shown, extract the overall total and attended numbers. "
        "Return STRICT JSON only, without markdown formatting, code fences, or explanations, in this exact format: "
        '{"total_classes": <int>, "attended_classes": <int>}'
    )

    try:
        async with ai_call_semaphore:
            completion = await asyncio.to_thread(
                active_client.chat.completions.create,
                model=GROQ_VISION_MODEL,
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": system_instruction},
                            {"type": "image_url", "image_url": {"url": data_url}},
                        ],
                    }
                ],
                temperature=0,
            )
        raw_text = str(completion.choices[0].message.content or "").strip()
    except RateLimitError:
        raise HTTPException(
            status_code=429,
            detail=(
                "A lot of students are using this right now. Please try again "
                "in about 30 seconds, or use manual entry instead."
            ),
        )
    except APIStatusError as e:
        raise HTTPException(
            status_code=502,
            detail=f"The AI service returned an error. Try again shortly. ({e.status_code})",
        )
    except Exception as e:
        raise HTTPException(
            status_code=502,
            detail=f"Couldn't reach the AI model right now. Try again shortly. ({e})",
        )

    # Defensive parsing: strip reasoning tokens (<think>...</think>) and code fences
    cleaned = re.sub(r"<think>.*?</think>", "", raw_text, flags=re.DOTALL).strip()
    cleaned = cleaned.replace("```json", "").replace("```", "").strip()

    json_match = re.search(r"\{[\s\S]*?\}", cleaned)
    json_str = json_match.group(0) if json_match else cleaned

    try:
        parsed = json.loads(json_str)
        total_classes = int(parsed.get("total_classes", parsed.get("total", 0)))
        attended_classes = int(parsed.get("attended_classes", parsed.get("attended", 0)))
        if total_classes <= 0:
            raise ValueError("Total classes must be > 0")
    except Exception:
        raise HTTPException(
            status_code=422,
            detail=(
                "Could not read the attendance data clearly from that screenshot. "
                "Try a clearer image, or enter your numbers manually."
            ),
        )

    return calculate_result(total_classes, attended_classes, None)


dist_dir = Path(__file__).resolve().parent.parent / "frontend" / "dist"
if (dist_dir / "assets").exists():
    app.mount("/assets", StaticFiles(directory=str(dist_dir / "assets")), name="assets")

@app.get("/")
def health_check(request: Request):
    dist_index = dist_dir / "index.html"
    if dist_index.exists() and "text/html" in request.headers.get("accept", ""):
        return FileResponse(dist_index)
    return {"status": "ok", "service": "AttendanceSafe API"}

@app.get("/health")
def api_health():
    return {"status": "ok", "service": "AttendanceSafe API"}
